package com.schoolpal.db.mybatis.inf;

import org.mybatis.spring.annotation.MapperScan;

import com.schoolpal.db.mybatis.model.TUser;

@MapperScan
public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    TUser selectByPrimaryKey(String cId);
    TUser selectLoginPassByLoginName(String cLoginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    int updateByPrimaryKey(TUser record);
}