package com.schoolpal.db.mybatis.model;

import java.util.Date;

public class TUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_loginname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cLoginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_loginpass
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cLoginpass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_realname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cRealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_nickname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_phone
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_email
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_qq
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_available
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private Boolean cAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_org_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_org_root_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cOrgRootId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_creator
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_create_time
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private Date cCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_last_visit_time
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private Date cLastVisitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_last_visit_ip
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    private String cLastVisitIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_id
     *
     * @return the value of t_user.c_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_id
     *
     * @param cId the value for t_user.c_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_loginname
     *
     * @return the value of t_user.c_loginname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcLoginname() {
        return cLoginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_loginname
     *
     * @param cLoginname the value for t_user.c_loginname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcLoginname(String cLoginname) {
        this.cLoginname = cLoginname == null ? null : cLoginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_loginpass
     *
     * @return the value of t_user.c_loginpass
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcLoginpass() {
        return cLoginpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_loginpass
     *
     * @param cLoginpass the value for t_user.c_loginpass
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcLoginpass(String cLoginpass) {
        this.cLoginpass = cLoginpass == null ? null : cLoginpass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_realname
     *
     * @return the value of t_user.c_realname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcRealname() {
        return cRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_realname
     *
     * @param cRealname the value for t_user.c_realname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcRealname(String cRealname) {
        this.cRealname = cRealname == null ? null : cRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_nickname
     *
     * @return the value of t_user.c_nickname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcNickname() {
        return cNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_nickname
     *
     * @param cNickname the value for t_user.c_nickname
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcNickname(String cNickname) {
        this.cNickname = cNickname == null ? null : cNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_phone
     *
     * @return the value of t_user.c_phone
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_phone
     *
     * @param cPhone the value for t_user.c_phone
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_email
     *
     * @return the value of t_user.c_email
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcEmail() {
        return cEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_email
     *
     * @param cEmail the value for t_user.c_email
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcEmail(String cEmail) {
        this.cEmail = cEmail == null ? null : cEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_qq
     *
     * @return the value of t_user.c_qq
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcQq() {
        return cQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_qq
     *
     * @param cQq the value for t_user.c_qq
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcQq(String cQq) {
        this.cQq = cQq == null ? null : cQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_available
     *
     * @return the value of t_user.c_available
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public Boolean getcAvailable() {
        return cAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_available
     *
     * @param cAvailable the value for t_user.c_available
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcAvailable(Boolean cAvailable) {
        this.cAvailable = cAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_org_id
     *
     * @return the value of t_user.c_org_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcOrgId() {
        return cOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_org_id
     *
     * @param cOrgId the value for t_user.c_org_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcOrgId(String cOrgId) {
        this.cOrgId = cOrgId == null ? null : cOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_org_root_id
     *
     * @return the value of t_user.c_org_root_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcOrgRootId() {
        return cOrgRootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_org_root_id
     *
     * @param cOrgRootId the value for t_user.c_org_root_id
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcOrgRootId(String cOrgRootId) {
        this.cOrgRootId = cOrgRootId == null ? null : cOrgRootId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_creator
     *
     * @return the value of t_user.c_creator
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcCreator() {
        return cCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_creator
     *
     * @param cCreator the value for t_user.c_creator
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcCreator(String cCreator) {
        this.cCreator = cCreator == null ? null : cCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_create_time
     *
     * @return the value of t_user.c_create_time
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public Date getcCreateTime() {
        return cCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_create_time
     *
     * @param cCreateTime the value for t_user.c_create_time
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcCreateTime(Date cCreateTime) {
        this.cCreateTime = cCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_last_visit_time
     *
     * @return the value of t_user.c_last_visit_time
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public Date getcLastVisitTime() {
        return cLastVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_last_visit_time
     *
     * @param cLastVisitTime the value for t_user.c_last_visit_time
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcLastVisitTime(Date cLastVisitTime) {
        this.cLastVisitTime = cLastVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_last_visit_ip
     *
     * @return the value of t_user.c_last_visit_ip
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public String getcLastVisitIp() {
        return cLastVisitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_last_visit_ip
     *
     * @param cLastVisitIp the value for t_user.c_last_visit_ip
     *
     * @mbg.generated Sun Jan 01 23:39:25 CST 2017
     */
    public void setcLastVisitIp(String cLastVisitIp) {
        this.cLastVisitIp = cLastVisitIp == null ? null : cLastVisitIp.trim();
    }
}